repositoryUrl": "https://github.com/apricote/Listory"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Build Docker Container
        docker build \
          -t apricote/listory \
          --build-arg VERSION=${nextRelease.version} \
          --build-arg GIT_COMMIT=`git rev-parse HEAD` \
          .

        # Update version in Helm Chart
        CHART_FILE=charts/listory/Chart.yaml

        sed -i \
          -e "s/version: .*/version: ${nextRelease.version}/g" \
          -e "s/appVersion: .*/appVersion: ${nextRelease.version}/g" \
          $CHART_FILE

        # Package Helm Chart
        mkdir .helm-chart
        helm package charts/listory --destination .helm-charts

  - - semantic-release-docker
    - name: apricote/listory
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - charts/listory/Chart.yaml
  - - "@semantic-release/github"
    - assets:
        - path: .helm-charts/listory-*.tgz
          label: Helm Chart
