{
 "title": "HTTP Endpoint",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Endpoint Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_count{status=\"2XX\"}[$__interval]) ) by (path) / sum(rate(http_requests_count[$__interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "API Response Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_bucket{status=\"2XX\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Endpoint call frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_requests_count[$__rate_interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}