global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "listory"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:9464"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3100"]
