name: Release
on:
  push:
    branches:
      - main
jobs:
  tests:
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.10.4"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.9.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install semantic-release
        run: npm install -g --legacy-peer-deps semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec semantic-release-docker

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release
